### PR TITLE
Rename AvroReadGroupGenomicRDD to AvroRecordGroupGenomicRDD.

### PR DESCRIPTION
**Pull request by heuermh**

### CODE REVIEW

**Comment by fnothaft** [comment]
+1! Thanks Michael!

**Comment by heuermh** [comment]
You're too quick!  I pushed another commit to this branch with WIP towards addressing the second review comment ... IDEA is broken on the new autogenerate stuff so I still need time to complete it.  Let's see, do I need to do another pull request?

**Comment by heuermh** [comment]
Shit, sorry, git has been letting me push to your remote by accident ... https://github.com/fnothaft/adam/commits/issues/1599-no-copy-no-mo

Damn you, IDEA!

**Comment by fnothaft** [comment]
I think I may have given you push permissions to my fork when we were working on the VariantContextConverter rewrite... No sweat though; just be mindful of such in the future ;)

**Pull request merged**
